### ISSUE TITLE
Copy content-types but not locales

### ISSUE THREAD

**Issue by matthieu-beteille** [contentful/contentful-space-sync#69]
Hi :hand:,

Is there a way to synchronise the content types and not the locales?

Cheers

**Comment by trodrigues** [comment]
Hi there,

there isn't a way right now, but this could possibly be added.

One of the reasons why it wasn't before is because entries will have content in a format such as:

```
{
  "fields": {
    "title": {
      "en-US": "english title",
      "pt-PT": "portuguese title"
    }
  }
}
```

So when you clone a content model, if you don't also clone the locales, the entries will fail to be copied because not all the expected locales are there.

But I understand there can be a potential use case for only copying content types if you want to start from scratch with only the same content types. Is that what you're trying to do?

**Comment by matthieu-beteille** [comment]
That's exactly what I want to do. I want to start with the exact same content types, and keep them in sync as I add more.

If you want I can create a PR adding a "skip-locales" option?

**Comment by trodrigues** [comment]
Hi there,

first of all, thanks for your PR :)

I only managed to have a look at it yesterday and I ended up moving the logic to the [contentful-batch-libs](https://github.com/contentful/contentful-batch-libs/commit/b14ab82b101694964349b6ab28282f4eaa191dd4) package as this is the package that implements most of the logic of this tool. I decided to just do it because it would be faster than asking you to do it there, and then having to merge PRs and all of that.

I just merged my own [PR](https://github.com/contentful/contentful-space-sync/pull/72) with this and it should be released soon via semantic-release.
