### ISSUE TITLE
Sync fails with --force-overwrite

### ISSUE THREAD

**Issue by matviyiv** [contentful/contentful-space-sync#89]
contentful-space-sync is failing if target space doesn't have Entry which was just created in source space.
I am using contentful-space-sync v3.2.2
Command:
contentful-space-sync --config config.json --skip-content-model --force-overwrite

**Comment by trodrigues** [comment]
This should only be a problem if the content type for that entry doesn't exist in the destination space. As you are using the skip-content-model option, that might be the cause of your problem.

**Comment by matviyiv** [comment]
I run model sync each time but in separate command:
contentful-space-sync --config config.json --content-model-only --force-overwrite
contentful-space-sync --config config.json --skip-content-model --force-overwrite
contentful-link-cleaner --config config2.json

But some times content type is not published on destination space.

**Comment by trodrigues** [comment]
That's probably the reason why you're seeing this problem. If the content type is not published, and the entry expects some of those changes to exist, then it won't be created.

In general the workflow you are following here doesn't sound like a good idea, because the only changes that this tool can make to content types are if you add or delete fields.

And deleting fields only works if the destination content type has no entries for that content type.

If you delete fields with any entries existing for that content type in the destination space, it will fail.

If you make any changes to existing fields, it will fail.

If you want to make more specific changes to content types over time you should consider looking into our [contentful-management.js](https://github.com/contentful/contentful-management.js) SDK and writing your own tools to make more specific changes to content types as this tool is probably not flexible enough for that you're trying to do.
