### ISSUE TITLE
Exceeds rate limit when syncing a large space

### ISSUE THREAD

**Issue by qbunt** [contentful/contentful-space-sync#96]
When this tool is used to sync a large space, the tool will overwhelm the rate limit of the Content Management API (presumably) and not allow any more assets or content models to sync.

When running, this tool (or the API) will allow for **exactly** 600 lines of output before a 'rate limit exceeded' message is received through the API [as soon through this scrollback](https://gist.github.com/qbunt/1ec80b475c91b5346ac4b33e3bac14e1).

I recognize that this could be an API issue AND a tool issue, but I thought it was worth posting here as well. Thanks!

**Comment by Khaledgarbaya** [comment]
Hi @qbunt , 

The tool already has a back-off and retry mechanism but only for the per second rate limit, but if you reach the hourly limit there is not much to do, tool wise, because it does not make sense to pause the sync for 20 min or more till the next hour and then continue.
One solution is sync gradually, for example: let's say you have 100 assets and you want to sync them in 2 times. You mark 50 as draft and then sync for the first time and keep the sync token around, 2nd iteration you mark the synced assets as drafts and the non synced ones as published etc...

Best,
Khaled

**Comment by qbunt** [comment]
Hey @Khaledgarbaya, thanks for the fast response. I have a call with our agency contact tomorrow. It does seem like the per second backoffs are being respected, it's the hour limit we're running up against. This space has 1600+ assets in it, and I think that may simply be too much for the system. 

One question for you. I agree it doesn't necessarily make sense to pause for 20+ minutes. You could conceivably run a sync on one specific content type, and process only the links connected to that content type, right?

**Comment by Khaledgarbaya** [comment]
Hi @qbunt it would a bit complicated if we try to only sync entries by contentTypes because some ContentTypes may link to other contenTypes, What we'll try to do at some point is maybe also wait for the rest of the hour and resume again, this way the sync will take longer but at least it will finish.

**Comment by sejoker** [comment]
@qbunt @Khaledgarbaya I have exactly the same problem in Auctionata. Our space is quite big as well. We do incremental syncing using sync token of the last successful sync (built-in in the tool ). We had to sync from scratch due to other issues and ended up overwhelm hourly rate limits. The solution which worked for us was overriding default timeouts in the [contentful management](https://github.com/contentful/contentful-management.js/blob/e818be53f7c7e42efd9e45912474af0a02f97136/lib/contentful-management.js#L39) package. I set
rateLimit: 1,
rateLimitPeriod: 5000

It worked for 2 days but ended up sync successfully.

My Feature request to @Khaledgarbaya  would be allow passing rateLimit and rateLimitPeriod directly to contentful-space-sync.

**Comment by Khaledgarbaya** [comment]
Hey @sejoker that's a good point also, I'll see what I can do

**Comment by Khaledgarbaya** [comment]
Ok it turns out it is easy for now to expose these two params once those PR are reviewed and merge you should have that option 

PRS : 

https://github.com/contentful/contentful-batch-libs/pull/70
https://github.com/contentful/contentful-space-sync/pull/99

**Comment by Khaledgarbaya** [comment]
@qbunt and @sejoker Guess what the PR are merged you should have a new version published soon, when the CI finishes building

**Comment by qbunt** [comment]
Ah you guys rock @Khaledgarbaya! Thanks so much for the fast response, I'll go through some testing early today with this and see where we land. Cheers!

**Comment by apaatsio** [comment]
I tried the sejoker's suggestion to set rateLimit: 1 and rateLimitPeriod: 5000 but I'm still getting a 429 Rate limit exceeded error after a while.

I'm trying to clone a space that has 2 content types, ~200 entries and ~1800 assets. I'm doing a fresh sync.

**Comment by Khaledgarbaya** [comment]
@apaatsio which version are you using ?

**Comment by apaatsio** [comment]
@Khaledgarbaya 4.1.3

**Comment by Khaledgarbaya** [comment]
I will investigate that asap, can you provide the the command line logs, also what you executed as a command? **please remove anything related to spaceIds and Tokens**

**Comment by apaatsio** [comment]
The log can be found here: https://gist.github.com/apaatsio/776e0b882fc6f804a5d005bbbc086f0d

When I check the failing asset (id 2AGLlAwmDeOUuQGOU6IAAE) in the destination space, it looks like this:
![processing](https://cloud.githubusercontent.com/assets/195210/21134273/b407beac-c125-11e6-88f8-755589d4c661.png)

Is this an error situation or how long should the processing take? It has been processing for at least 20 minutes.

**Comment by Khaledgarbaya** [comment]
@apaatsio Unfortunately this is hard to track 😔  could happen due to multiple reasons. For the image above it will stay like that.

Meanwhile can you try the [contentful-export](https://github.com/contentful/contentful-export) and [contentful-import](https://github.com/contentful/contentful-import) .

Sorry again for this issue it is hard to track since there is a lot of network operations, but I will investigate why the with that configs you still hit the rate limit.
